name: Jenkins Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger Jenkins Pipeline
        run: curl -X POST ${{ secrets.JENKINS_WEBHOOK_URL }}
